ticket:10272: the clang workaround was only *mostly* harmless. Disable it under Windows.    Fix: typeinfo(82): error C2874: using-declaration causes a multiple declaration of 'type_info' X-Commit-URL: https://ssl.icu-project.org/trac/changeset/35375 Former-commit-id: e56935836ec59bbde84516fb99131cf7f35559f3